### PR TITLE
feat(terraform): Upgrade datadog terraform provider to v3.12.0

### PR DESCRIPTION
**Pull request by Lax77**
Signed-off-by: Lax Kota <lkota@guidewire.com>
Signed-off-by: Nimish Pawar <npawar@guidewire.com>

### Description of your changes

Fixes # https://github.com/crossplane-contrib/provider-jet-datadog/issues/10

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
We have tested following [this] document were able to create and delete synthetic tests fine with these changes.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by ytsarev — COMMENTED** [review]
Thanks a lot for the contribution. Could you please rebase with main after we merged https://github.com/crossplane-contrib/provider-jet-datadog/pull/9 ?

**Comment by Lax77** [comment]
> Thanks a lot for the contribution. Could you please rebase with main after we merged #9 ?

Sure, just rebased the branch. Could you review it again?

**Comment by ytsarev** [comment]
@Lax77 thanks a lot! Did you also regenerate with `make reviewable` ? I might be wrong, but I am expecting the new [Downtime CRD](https://github.com/crossplane-contrib/provider-jet-datadog/pull/9/files#diff-461055adf64e54edc26a9e9af6f4efe149f8f5ed4c033c87bdb95f7405eb848a) to be also involved in the diff

**Comment by Lax77** [comment]
@ytsarev No, I only rebased earlier. Re-ran the `make reviewable` and pushed the changes again. 

This time it updated the [downtime CRD](https://github.com/crossplane-contrib/provider-jet-datadog/pull/11/files#diff-461055adf64e54edc26a9e9af6f4efe149f8f5ed4c033c87bdb95f7405eb848a) with v3.12.0 specific changes. Along with CRD, apis in downtime/v1alpha1 were also updated.

**Review by ytsarev — APPROVED** [review]
Sweet, thanks a lot for the branch update

**Pull request merged**
